name: CI

on: [push]

jobs:

  clojure:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # It is important to install java before installing clojure tools which needs java
      # exclusions: babashka, clj-kondo and cljstyle
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.3
        with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          cli: 1.10.1.693              # Clojure CLI based on tools.deps
          lein: 2.9.1                  # Leiningen
          clj-kondo: 2022.05.31        # clj-kondo
          cmd-exe-workaround: 'latest' # Replaces `clojure` with `deps.clj` on Windows

      - name: Show leiningen version
        run: lein -v

      - name: Unit tests
        run: lein test

      - name: Show clj-kondo version
        run: clj-kondo --version

      - name: clj-kondo lint
        run: clj-kondo --lint src-clj/ test/
